### ISSUE TITLE
[루틴] routine_tb에 task_id 중복 삽입 가능

### ISSUE THREAD

**Issue by ybell1028** [depromeet/imgoing-backend#10]
![image](https://user-images.githubusercontent.com/54519245/135562208-2ad1612d-61dc-4b1f-99ea-ce7b80b165de.png)

![image](https://user-images.githubusercontent.com/54519245/135562232-76d0e552-f325-4935-af0c-faffd430c8c5.png)

**Comment by bluayer** [comment]
기능 변경으로 인해 이슈 닫음
